### PR TITLE
fix: return backend errors to the client

### LINKED ISSUE #89: Backend errors not properly handled
When querying through Lokxy, if the backend (e.g., Loki) returns an error message instead of a valid JSON response, Lokxy still attempts to parse it as a loghttp.QueryResponse.
This results in misleading parsing errors instead of propagating the real backend error to the client.

Error logs:

```sh
{"err":"invalid character 'p' looking for beginning of value","level":"error","msg":"Failed to unmarshal into loghttp.QueryResponse","ts":"2025-09-09T15:51:07.57882597Z"}
{"err":"invalid character 'p' looking for beginning of value","level":"error","msg":"Failed to unmarshal stats response","ts":"2025-09-09T15:51:07.610065822Z"}
```

To Reproduce:
	1.	Run a Loki query with invalid syntax or unsupported expression (example: `{region=~".*"} |= `).
	2.	Observe that the backend (Loki) returns a plain-text error, such as: `parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value. For instance, app=~".*" does not meet this requirement, but app=~".+" will`
	3. Lokxy attempts to unmarshal this plain text response as JSON, leading to a invalid character 'p' looking for beginning of value error. 

Expected behavior:

Lokxy should:
	•	Detect when the backend response is not valid JSON.
	•	Surface the real backend error message back to the client, instead of returning JSON unmarshal errors.
	•	Possibly (?) wrap it with some context like backend name (e.g., "backend1 error: <message>").

Below is a screenshot with the difference output between Lokxy (Left) and Loki (right)

Image

### PR DESCRIPTION
**Pull request by paulojmdias**
Errors will be returned in the format `{servergroup}: {error}`

image

Closes #89

### CODE REVIEW

File: pkg/proxy/proxy_test.go [hunk 1]
```diff
@@ -357,5 +339,89 @@ func TestProxy_ApiRoutes_Dispatch(t *testing.T) {
...
+	errorBody := "backend error from sg2"
+
+	// Only failing backend - to ensure deterministic behavior
+	s1 := mkUpstreamServer(t, map[string]http.HandlerFunc{
+		"/loki/api/v1/labels": func(w http.ResponseWriter, _ *http.Request) {
+			w.WriteHeader(http.StatusInternalServerError)
+			io.WriteString(w, errorBody)
+		},
+	})
+	defer s1.Close()
```
Comment (erka) [inline pkg/proxy/proxy_test.go]: it's better to use `t.Cleanup`

File: pkg/proxy/proxyresponse/types.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+// ForwardBackendError sends a simple error response: {backend}: {error}
+func ForwardBackendError(w http.ResponseWriter, backendName string, statusCode int, bodyBytes []byte, logger log.Logger) {
+	level.Error(logger).Log(
+		"msg", "Forwarding backend error to client",
+		"backend", backendName,
+		"status", statusCode,
+	)
+
+	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
+	w.WriteHeader(statusCode)
```
Comment (heliapb) [inline pkg/proxy/proxyresponse/types.go]: I wonder if we could not just simplify this, and instead of `w.Header().Set("Content-Type", "text/plain; charset=utf-8")`, add the backend here something like:
```go
	w.Header().Set("Failed-Backend", backendName)
```

File: pkg/proxy/proxyresponse/types.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+// ForwardConnectionError sends a connection error response: {backend}: {error}
+// Uses 502 Bad Gateway to indicate the backend was unreachable
+func ForwardConnectionError(w http.ResponseWriter, backendErr *BackendError, logger log.Logger) {
+	level.Error(logger).Log(
+		"msg", "Forwarding connection error to client",
+		"backend", backendErr.BackendName,
+		"err", backendErr.Err,
+	)
+
+	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
```
[the remark this answers is not in the document]
Comment (paulojmdias) [reply pkg/proxy/proxyresponse/types.go]: I added your suggestion and updated the tests accordingly to validate it.

**Review by heliapb — APPROVED** [review]
Lgtm
